
iam = "mud-engine-1"
url = "10.225.83.50"
port = 8283
logdir = "/var/logs/flux"


[cluster]
name = "flux1-cluster"
address = "localhost"
port = 8281
scramble = true

[jwt]
level = "client"
secret = "ldkj03hd3oidh3oidh3odi3hdoi3hdoih3odih3do3idh3iofhoih3"
    [[jwt.claim]]
    key = "flux-reader"
    value = "true"

    [[jwt.claim]]
    key = "flux-writer"
    value = "false"

