package internal

var (
	CONTROL_CONNECT           = "CONN"
	CONTROL_TOPIC_SUBSCRIBE   = "TOP+"
	CONTROL_TOPIC_UNSUBSCRIBE = "TOP-"
	CONTROL_NODE_COMM         = "NODE"
	CONTROL_MESSAGE_TEXT      = "TEXT"
)
