package capacitor

var (
	FLUX_TYPE_CONNECTION_REQUEST  = "FLUX-CONN-REQ"
	FLUX_TYPE_CONNECTION_RESPONSE = "FLUX-CONN-RESP"
	FLUX_TYPE_TOPIC_SUBSCRIPTION  = "FLUX-TOPIC-SUBSCRIBE"
	FLUX_TYPE_STANDARD_MESSAGE    = "FLUX-STANDARD-MESSAGE"
	FLUX_TYPE_SYSTEM_PING         = "FLUX-SYSTEM-PING"
)
